// animations.h - Master file with all animation includes and array
#ifndef MASTER_ANIMATIONS_H
#define MASTER_ANIMATIONS_H

#include "animation_types.h"

#include "eye_scan.h"
#include "cats_walking.h"
#include "monochrom_smiley.h"
#include "pirate_flag.h"
#include "candle.h"
#include "amongus.h"
#include "dinos_colors.h"
#include "penguin.h"
#include "loading.h"
#include "game_over.h"
#include "figures_tetris.h"
#include "lemur.h"
#include "cat.h"
#include "jumping_duck.h"
#include "ps_symbols.h"
#include "fireworks.h"
#include "chip.h"
#include "mtv.h"
#include "tetris.h"
#include "smiley.h"
#include "coffee.h"
#include "wow.h"
#include "rainbow_chekered.h"
#include "ducks_colors.h"
#include "dino.h"
#include "countdown.h"
#include "nemo.h"
#include "queen.h"
#include "eyes_pop.h"
#include "waves.h"
#include "sonic.h"
#include "golden_ring.h"
#include "laughing_minion.h"
#include "frog.h"
#include "red_heart.h"
#include "netflix.h"
#include "flash.h"
#include "rainbow_skull.h"
#include "snake_eye.h"
#include "gnome.h"
#include "santa_eating_candy.h"
#include "matrix.h"
#include "halloween.h"
#include "sponge_bob.h"
#include "pokeball.h"
#include "barbers.h"
#include "plane_window.h"
#include "hearts.h"
#include "beer.h"
#include "minion.h"
#include "parrot.h"
#include "shark.h"
#include "smiley_with_a_tongue.h"
#include "uss_enterprise.h"
#include "abduction.h"
#include "colorful_gates.h"
#include "stop.h"
#include "spiderman.h"
#include "licking_lips.h"
#include "jackson.h"
#include "panda_eating_grass.h"
#include "charlie_chaplin.h"
#include "christmas_tree.h"

// Global array of all available animations
const Animation allAnimations[] = { eye_scanAnimation, cats_walkingAnimation, monochrom_smileyAnimation, pirate_flagAnimation, candleAnimation, amongusAnimation, dinos_colorsAnimation, penguinAnimation, loadingAnimation, game_overAnimation, figures_tetrisAnimation, lemurAnimation, catAnimation, jumping_duckAnimation, ps_symbolsAnimation, fireworksAnimation, chipAnimation, mtvAnimation, tetrisAnimation, smileyAnimation, coffeeAnimation, wowAnimation, rainbow_chekeredAnimation, ducks_colorsAnimation, dinoAnimation, countdownAnimation, nemoAnimation, queenAnimation, eyes_popAnimation, wavesAnimation, sonicAnimation, golden_ringAnimation, laughing_minionAnimation, frogAnimation, red_heartAnimation, netflixAnimation, flashAnimation, rainbow_skullAnimation, snake_eyeAnimation, gnomeAnimation, santa_eating_candyAnimation, matrixAnimation, halloweenAnimation, sponge_bobAnimation, pokeballAnimation, barbersAnimation, plane_windowAnimation, heartsAnimation, beerAnimation, minionAnimation, parrotAnimation, sharkAnimation, smiley_with_a_tongueAnimation, uss_enterpriseAnimation, abductionAnimation, colorful_gatesAnimation, stopAnimation, spidermanAnimation, licking_lipsAnimation, jacksonAnimation, panda_eating_grassAnimation, charlie_chaplinAnimation, christmas_treeAnimation };
const uint8_t TOTAL_ANIMATIONS = sizeof(allAnimations) / sizeof(Animation);

#endif // MASTER_ANIMATIONS_H